application: modifiedsingle
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /asdf
  static_files: static/modifiedsingle.html
  upload: modifiedsingle\.html
  login: required

- url: /static/
  static_dir: static

- url: /.*
  script: ms.app
  login: optional

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

