application: modifiedsingle
version: 1
runtime: python
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: static/modifiedsingle.html
  upload: modifiedsingle\.html

- url: /static/
  static_dir: static

- url: /.*
  script: ms.app

