ranks = ["PRO","SP","AAA","AA","A","B","C"];
races ={"PRO":{"PRO":[5,5],"SP":[6,5],"AAA":[6,4],"AA":[6,3],"A":[7,3],"B":[7,2],"C":[8,2],"Bye":[0,0]},
        "SP" :{"PRO":[5,6],"SP":[5,5],"AAA":[5,4],"AA":[5,3],"A":[6,3],"B":[6,2],"C":[7,2],"Bye":[0,0]},
        "AAA":{"PRO":[4,6],"SP":[4,5],"AAA":[4,4],"AA":[4,3],"A":[5,3],"B":[5,2],"C":[6,2],"Bye":[0,0]},
        "AA" :{"PRO":[3,6],"SP":[3,5],"AAA":[3,4],"AA":[4,4],"A":[4,3],"B":[4,2],"C":[5,2],"Bye":[0,0]},
        "A"  :{"PRO":[3,7],"SP":[3,6],"AAA":[3,5],"AA":[3,4],"A":[3,3],"B":[3,2],"C":[4,2],"Bye":[0,0]},
        "B"  :{"PRO":[2,7],"SP":[2,6],"AAA":[2,5],"AA":[2,4],"A":[2,3],"B":[2,2],"C":[3,2],"Bye":[0,0]},
        "C"  :{"PRO":[2,8],"SP":[2,7],"AAA":[2,6],"AA":[2,5],"A":[2,4],"B":[2,3],"C":[2,2],"Bye":[0,0]},
        "Bye"  :{"PRO":[0,08],"SP":[0,0],"AAA":[0,0],"AA":[0,0],"A":[0,0],"B":[0,0],"C":[0,0],"Bye":[0,0]}
        };

players = [{'name':'Harold', 'rank':'AAA'},
           {'name':'Georgianne', 'rank':'B'},
           {'name':'SteveO', 'rank':'AAA'},
           {'name':'Rus', 'rank':'A'},
           {'name':'Fisher', 'rank':'AAA'},
           {'name':'Ram', 'rank':'A'},
           {'name':'NickH', 'rank':'SP'},
           {'name':'Sergin', 'rank':'A'},
           {'name':'JohonyW', 'rank':'AA'},
           {'name':'AlexM', 'rank':'AA'},
           {'name':'Sagar', 'rank':'AA'},
           {'name':'Horia', 'rank':'PRO'},
           {'name':'Kiran', 'rank':'A'},
           {'name':'Raj', 'rank':'AA'},
           {'name':'Beth', 'rank':'A'},
           {'name':'Vishnu', 'rank':'A'},
           {'name':'Brandon', 'rank':'SP'},
           {'name':'MickC', 'rank':'AA'},
           {'name':'RonB', 'rank':'AAA'},
           {'name':'Mary', 'rank':'A'},
           {'name':'Josh', 'rank':'AA'},
           {'name':'CJ', 'rank':'PRO'},
           {'name':'BenA', 'rank':'AAA'},
           {'name':'Dpham', 'rank':'A'},
           {'name':'Chrishina', 'rank':'A'}
          ];
